### ISSUE TITLE
Getting {'ELEMENT': NULL} calling AppiumWebElement.toJson

### ISSUE THREAD

**Issue by snickersv2** [KazuCocoa/appium_dart#13]
Hi, i am trying out this tool for Webview debugging. It seems I was able to find a specific textfield as an AppiumWebElement from a WebView but the i couldn't get its id.

Would like to ask for your advise.

Thank you.

**Comment by KazuCocoa** [comment]
It extends WebElement in webdriver.dart
Does https://pub.dev/documentation/webdriver/latest/webdriver.sync_io/WebElement-class.html help you?

**Comment by snickersv2** [comment]
Do you mean to cast it as that class? If yes, it did not work for me and I got a casting error.
I'm curious because I see in the appium server the following logs
_Got response with status 200: {"sessionId":"e2d76d3172ea6edd928881e970e84478","status":0,"value":{"ELEMENT":"0.803838448465809-4"}}_

but I'm finding out how to retrieve this element id and found this result when i called toJson() function
{ELEMENT: null}

I'm essentially trying to click a button from the WebView but calling AppiumWebElement.click() is not working for me. Is there something more to it?

**Comment by KazuCocoa** [comment]
No.
I meant like below code:

https://github.com/KazuCocoa/appium_dart/blob/master/test/functional/appium_dart_test.dart#L28-L30

```
var element = await driver.findElement(AppiumBy.accessibilityId(buttons));
expect(element.id != null, true);
await element.click();
```

So, I thought you can get id like `element.id`.
Could you share your server-side log with me?

**Comment by snickersv2** [comment]
hi, i see. I tried it and element.id returns null.
Here is the log i had:
[appium-server-side-log.txt](https://github.com/KazuCocoa/appium_dart/files/3474007/appium-server-side-log.txt)

I notice when that it finds an element and returns the following response for example:
Got response with status 200: {"sessionId":"7ab59e2a9bf57bdb8f4107a3f6d7daf5","status":0,"value":**{"ELEMENT":"0.5460738947949588-3"}}**

Is this the element id then?

**Comment by KazuCocoa** [comment]
Thanks. Gotcha.
Yeah, currently this parses only W3C format.
https://github.com/KazuCocoa/appium_dart/pull/14 will fix it
