### ISSUE TITLE
investigate integration_test

### ISSUE THREAD

**Issue by KazuCocoa** [KazuCocoa/appium_dart#28]
This is not an issue for this repository itself, but related to.

It needs to understand how they work
https://pub.dev/packages/integration_test
https://medium.com/flutter/updates-on-flutter-testing-f54aa9f74c7e

**Comment by KazuCocoa** [comment]
Espresso plugin allows to run with Flutter as App-in-App. It requires Flutter layer to have `enableFlutterDriverExtension`. Then, flutter layer can open the DartVM port.
https://pub.dev/packages/espresso

**Comment by KazuCocoa** [comment]
The integration_test calls `IntegrationTestWidgetsFlutterBinding.ensureInitialized()` https://github.com/flutter/flutter/blob/e5322acc77f116803c93cfe1d538ae3c16a19423/packages/integration_test/lib/integration_test.dart#L28
https://github.com/flutter/flutter/blob/e5322acc77f116803c93cfe1d538ae3c16a19423/packages/integration_test/lib/integration_test.dart#L122-L128

It was subclass of `LiveTestWidgetsFlutterBinding` extends `TestWidgetsFlutterBinding`
https://github.com/flutter/flutter/blob/7b251f5f37b2b10334752da6bed1f5b136f0cb4b/packages/flutter_test/lib/src/binding.dart#L1388
https://github.com/flutter/flutter/blob/7b251f5f37b2b10334752da6bed1f5b136f0cb4b/packages/flutter_test/lib/src/binding.dart#L167

**Comment by KazuCocoa** [comment]
https://flutter.dev/docs/testing/integration-tests
It seems `flutter_driver` remains as an optional way, but `integration_test` will be a recommended way.
`enableFlutterDriverExtension()` exposes Dart VM for testing, but probably they're moving to run all methods on the Dart VM like current Widget tests even for `integration_test`.

`flutter_driver` requires connecting to Dart VM over websocket. So, appium-flutter-driver also can connect to the Dart VM via WebSocket. If `integration_test` does everything on Dart VM (so it requires test code also in the same package), appium-flutter-driver will not work with the mode, while it still requires `enableFlutterDriverExtension()`.

I guess the background is iOS's restriction. To keep the privilege to UI components for testing as stable/reliable way, such limitation does not help. So, they're moving tests in the VM world to limit the area.

So, the `integration_test` is not E2E like `flutter_driver`, but it is similar to Espresso. Widget and integration test is not so different technically, I guess, but they have a bit different feature. Widget is more focusing on small components.


Another thought is https://github.com/KazuCocoa/proto-flutter-driver-server . The concept is to launch a web server on Dart VM and communicate with Appium over the connection. It calls `flutter_driver` methods to handle UI components, so potentially the structure can work with `integration_test`.

**Comment by KazuCocoa** [comment]
`integration_test` exposed the Dart port, but their commands were different from `flutter_driver`'s one.
appium-flutter-driver won't work with the `integration_test`. It requires updating methods at least

**Comment by phamnhuvu-dev** [comment]
> appium-flutter-driver won't work with the integration_test
@KazuCocoa Because app `integration_test` is self-driving testing, it means the application drives itself to run the test while `flutter_driver` has an isolate driver the application to run the test.
