### ISSUE TITLE
Cannot createDriver if 'automationName: "flutter" ' in desired capability

### ISSUE THREAD

**Issue by haitranA** [KazuCocoa/appium_dart#32]
I tried to create a Appium Driver via automationName:'flutter'. However, I got failed as following error message:

![Screen Shot 2021-07-26 at 11 27 46 AM](https://user-images.githubusercontent.com/86308842/127024791-d1f9b5de-f169-40e8-9d4b-a84c6b9a3c3e.png)

Appium log:

> (node:60267) [DEP0128] DeprecationWarning: Invalid 'main' field in '/usr/local/lib/node_modules/appium/node_modules/mjpeg-server/package.json' of './lib/mpegserver'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)
[Appium] Welcome to Appium v1.21.0
[Appium] Non-default server args:
[Appium]   sessionOverride: true
[Appium]   defaultCapabilities: {
[Appium]     newCommandTimeout: 600000
[Appium]   }
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   newCommandTimeout: 600000
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"capabilities":{"alwaysMatch":{"platformName":"Android","appium:automationName":"flutter","appium:app":"/Users/hai.tran/Desktop/appium_test/my_app/build/app/outputs/flutter-apk/app-debug.apk","appium:platformVersion":"12","appium:deviceName":"emulator-5554","appium:appPackage":"com.example.my_app","appium:appActivity":"MainActivity","appium:appWaitActivity":"MainActivity","appium:appWaitPackage":"com.example.my_app","appium:appWaitDuration":600000,"appium:newCommandTimeout":60000,"appium:udid":"emulator-5554","appium:chromedriverExecutable":"/Users/hai.tran/Desktop/mobile_platform_test/integration_test/chromedriver"},"firstMatch":[{}]}}
[debug] [W3C] Calling AppiumDriver.createSession() with args: [null,null,{"alwaysMatch":{"platformName":"Android","appium:automationName":"flutter","appium:app":"/Users/hai.tran/Desktop/appium_test/my_app/build/app/outputs/flutter-apk/app-debug.apk","appium:platformVersion":"12","appium:deviceName":"emulator-5554","appium:appPackage":"com.example.my_app","appium:appActivity":"MainActivity","appium:appWaitActivity":"MainActivity","appium:appWaitPackage":"com.example.my_app","appium:appWaitDuration":600000,"appium:newCommandTimeout":60000,"appium:udid":"emulator-5554","appium:chromedriverExecutable":"/Users/hai.tran/Desktop/mobile_platform_test/integration_test/chromedriver"},"firstMatch":[{}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1627316984903 (11:29:44 GMT-0500 (Central Daylight Time))
[Appium] Appium v1.21.0 creating new FlutterDriver (v0.0.28) session
[debug] [Appium] There are no active sessions for cleanup
[debug] [BaseDriver] Creating session with MJSONWP desired capabilities: null
[BaseDriver] SessionNotCreatedError: A new session could not be created. Details: The desiredCapabilities object was not valid for the following reason(s): 'platformName' can't be blank; 'automationName' can't be blank
[BaseDriver]     at FlutterDriver.validateDesiredCaps (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/node_modules/appium-base-driver/lib/basedriver/driver.js:226:25)
[BaseDriver]     at FlutterDriver.validateDesiredCaps (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/lib/driver.ts:88:23)
[BaseDriver]     at FlutterDriver.createSession (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/node_modules/appium-base-driver/lib/basedriver/commands/session.js:46:8)
[BaseDriver]     at FlutterDriver.createSession (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/lib/driver.ts:67:37)
[BaseDriver]     at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:387:43)
[BaseDriver]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1627316985659 (11:29:45 GMT-0500 (Central Daylight Time))
[debug] [W3C] Encountered internal error running command: SessionNotCreatedError: A new session could not be created. Details: The desiredCapabilities object was not valid for the following reason(s): 'platformName' can't be blank; 'automationName' can't be blank
[debug] [W3C]     at FlutterDriver.validateDesiredCaps (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/node_modules/appium-base-driver/lib/basedriver/driver.js:226:25)
[debug] [W3C]     at FlutterDriver.validateDesiredCaps (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/lib/driver.ts:88:23)
[debug] [W3C]     at FlutterDriver.createSession (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/node_modules/appium-base-driver/lib/basedriver/commands/session.js:46:8)
[debug] [W3C]     at FlutterDriver.createSession (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/lib/driver.ts:67:37)
[debug] [W3C]     at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:387:43)
[debug] [W3C]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[HTTP] <-- POST /wd/hub/session 500 786 ms - 1244
[HTTP] 

My desired capability is following:
>var localServer = Uri.parse('http://127.0.0.1:4723/wd/hub/');
  var dc = {
    'platformName': 'Android',
    'automationName': 'flutter',
    'app': File( '/Users/hai.tran/Desktop/appium_test/my_app/build/app/outputs/flutter-apk/app-debug.apk').absolute.path,
    'platformVersion': '12',
    'deviceName': 'emulator-5554',
    'appPackage': 'com.example.my_app',
    'appActivity': 'MainActivity',
    'appWaitActivity': 'MainActivity',
    'appWaitPackage': 'com.example.my_app',
    'appWaitDuration': 600000,
    'newCommandTimeout': 60000,
    'udid': 'emulator-5554',
    'chromedriverExecutable':  '/Users/hai.tran/Desktop/mobile_platform_test/integration_test/chromedriver',

setUpAll(() async {
    driver = await createDriver(desired: dc, uri: localServer);
    // await driver.timeouts.setImplicitTimeout(const Duration(seconds: 5));
  });

  tearDownAll(() async {
    await driver.quit();
  });

When I replace automationName to 'UiAutomator2', it works normally.  I also tried to create an Appium Server with automationName='flutter' in python. It works well.

Would you please share me how to solve this problem?

Thank you.

**Comment by KazuCocoa** [comment]
Could you try out `appium@beta` or `appium@rc`?

> [Appium] Appium v1.21.0 creating new FlutterDriver (v0.0.28) session

Flutter driver 0.0.29 can accept W3C spec capabilities, but older ones only accepted non-W3C capabilities.
This dart client works as W3C WebDriver protocol.

**Comment by haitranA** [comment]
It is not reproduced after I tried apapium@beta instead of version 1.21.0. Close it.
