### ISSUE TITLE
[HELP] How to wait for in appium dart

### ISSUE THREAD

**Issue by haitranA** [KazuCocoa/appium_dart#33]
I need wait for element visible and invisible in timeout for NATIVE_APP and FLUTTER contexts. How do I use it in appium driver in dart?

Thank you

**Comment by KazuCocoa** [comment]
For flutter, `waitFor` in https://github.com/truongsinh/appium-flutter-driver. The finder is probably https://github.com/KazuCocoa/appium_dart/blob/172a53e43d0375fbff92c0e32438949212ad116e/lib/src/common/flutter_finder.dart#L9 is fine.

For native context, you can use https://api.flutter.dev/flutter/webdriver.support.async/Clock/waitFor.html I guess.

**Comment by haitranA** [comment]
Thank you

**Comment by KazuCocoa** [comment]
Not flutter specific, but in general, you should make unique each element (if possible) to prevent your situation. (confusing which element is the right one)

**Comment by haitranA** [comment]
I know that we try to use a locator's type which is unique to find, but if I have no choice, except Type for finding.

For example, there are 2 elements which have the same Type, and I use finder by type, so it returns 2 elements which match with this finder. If I want to tap on second elements, how do I do that? 

In flutter_driver, we can do it via following code:
`find.byType(Icon).at(<index>)`

**Comment by KazuCocoa** [comment]
I haven't experienced flutter well.
I think https://github.com/truongsinh/appium-flutter-driver or appium forum may help rather than here
