### ISSUE TITLE
Format all the code on pull request

### ISSUE THREAD

**Issue by guyluz11** [KazuCocoa/appium_dart#36]
We can increase this package points in [pub.dev score page](https://pub.dev/packages/appium_driver/score) just by running `dart format .`

![image](https://user-images.githubusercontent.com/9304740/141678328-852f5360-303f-49fe-8e5c-0cce7d0b33e7.png)

I have recently got pr that is doing GitHub actions that automatically will format all the code on pull requests from dev branch to master branch.
The format will work only for the main repo, will not work on pr from forks due to GitHub's security reasons.

Would you like me to create a pull request for that?.

**Comment by KazuCocoa** [comment]
thanks. I've fixed them with the latest dart 2.14.4
