### ISSUE TITLE
Can we support more platforms?

### ISSUE THREAD

**Issue by guyluz11** [KazuCocoa/appium_dart#37]
I saw in [pub.dev score page](https://pub.dev/packages/appium_driver/score) that we are losing 10 points because we don't support js runtime.

![image](https://user-images.githubusercontent.com/9304740/141678563-6a7ead51-a1ca-4308-8e0a-3875e27c77d1.png)

This is a common issue with packages, most of the time replacing [dart:io](https://api.dart.dev/stable/2.14.4/dart-io/dart-io-library.html) with [universal_io](https://pub.dev/packages/universal_io) will fix the issue.
It has the same method names so it is just adding dependency and replacing the import.

We should give it a try and test if this still works in flutter web with `universal_io`.

**Comment by KazuCocoa** [comment]
My understanding of this is to support web environment.
I don't have the motivation to make this lib work on web . (In the case, I'd recommend webdriverio for JS and web2driver for Web usage)
