### ISSUE TITLE
Could not proxy command to the remote server. Original error: socket hang up

### ISSUE THREAD

**Issue by lorenacimpean** [KazuCocoa/appium_dart#39]
Hi,

I-m trying to run the tests from your example-appium-flutter-dart repo: https://github.com/KazuCocoa/example-appium-flutter-dart 

I'm getting Could not proxy command to the remote server. Original error: socket hang up.

I ran the tests with uiautomator2, but when I switch to flutter, I keep gettings errors, it seems to me like it might be a configuration issue, but I'm running out of ideas.

I attached the appium logs, dart test logs and main_test.dart file.

[main_test.dart.txt](https://github.com/KazuCocoa/appium_dart/files/8062189/main_test.dart.txt)
[dart_test_logs.txt](https://github.com/KazuCocoa/appium_dart/files/8062190/dart_test_logs.txt)
[appiumLogs.txt](https://github.com/KazuCocoa/appium_dart/files/8062191/appiumLogs.txt)

**Comment by KazuCocoa** [comment]
Let me take a look.

The error occurred in:
```
[debug] [WD Proxy] Proxying [GET /appium/device/pixel_ratio] to [GET http://127.0.0.1:8200/session/d59f528c-7b59-49c1-b2c9-530a87747175/appium/device/pixel_ratio] with no body
[WD Proxy] socket hang up
```

**Comment by KazuCocoa** [comment]
1. What about changing `skipServerInstallation` as `false`?
2. Could you provide the device logcat?

I've fixed a dependency in appium-flutter-driver as 1.0.1, so could you try the one as well?

I ran the same command on an emulator with appium v2.0.0-beta.25 and 1.0.1 flutter driver. It worked. (Commented out `await driver.device.shake();` though)

**Comment by lorenacimpean** [comment]
I reinstalled the flutter appium driver so it would update to v1.0.1, set skipServerInstallation to false and commented out  `await driver.device.shake();`.

I'm now getting this error:
APPIUM ERROR:
[debug] [W3C] Encountered internal error running command: TypeError: Cannot read properties of undefined (reading 'match') 
debug] [W3C]     at processLogToGetobservatory (/Users/user/.appium/appium-flutter-driver/node_modules/appium-flutter-driver/build/driver/lib/sessions/observatory.js:124:9)
[debug] [W3C]     at getObservatoryWsUri (/Users/user/.appium/appium-flutter-driver/node_modules/appium-flutter-driver/lib/sessions/android.ts:40:47)
[debug] [W3C]     at startAndroidSession (/Users/user/.appium/appium-flutter-driver/node_modules/appium-flutter-driver/lib/sessions/android.ts:27:49)
[debug] [W3C]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[debug] [W3C]     at FlutterDriver.createSession (/Users/user/.appium/appium-flutter-driver/node_modules/appium-flutter-driver/lib/sessions/session.ts:22:47)
[debug] [W3C]     at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:251:35)

LOGCAT ERROR:  UnknownException (500): An unknown server-side error occurred while processing the command. Original error: Cannot read properties of undefined (reading 'match') 
  package:webdriver/src/handler/w3c/utils.dart 99:9         parseW3cResponse
  package:appium_driver/src/handler/w3c/session.dart 25:21  W3cSessionHandler.parseCreateResponse
  package:webdriver/src/common/request_client.dart 96:32    AsyncRequestClient.send
  ===== asynchronous gap ===========================
  package:appium_driver/async_core.dart 60:19               createDriver
  ===== asynchronous gap ===========================
  appium-test/main_test.dart 10:14                          main.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart                                      _CustomZone.bindUnaryCallbackGuarded.<fn>

I attached the logs and main_test.dart file.

[main_test.dart.txt](https://github.com/KazuCocoa/appium_dart/files/8067896/main_test.dart.txt)
[dart_test_logs.txt](https://github.com/KazuCocoa/appium_dart/files/8067897/dart_test_logs.txt)
[appiumLogs.txt](https://github.com/KazuCocoa/appium_dart/files/8067898/appiumLogs.txt)

**Comment by KazuCocoa** [comment]
Current issue is below:
https://github.com/appium-userland/appium-flutter-driver/search?q=match&type=issues

What about the device logcat?
appium-flutter-driver expects https://github.com/appium-userland/appium-flutter-driver/blob/main/driver/lib/sessions/observatory.ts#L142-L145 in logcat.


Current issue is appium-flutter-driver one, so close this issue for now. (since it is not this dart client side issue)
