### ISSUE TITLE
Why is the source code not full?

### ISSUE THREAD

**Issue by mygoa** [KazuCocoa/appium_dart#41]
Hi, 

I tried to get the soyrce code to make sure my webElement were present, but it turns out that I could only have a part of the source code. Here is my code: 

  late AppiumWebDriver driver;
  driver = await createDriver(
      uri: Uri.parse('http://192.168.1.158:4723/wd/hub/'),
      desired: {
        'platformName': 'Android',
        'platformVersion': '12',
        'deviceName': 'Android Emulator',
        'browserName': 'Chrome',
        'automationName': 'Appium',
      });
  await driver.get("https://www.google.com");
  String source = await driver.pageSource;
  print(source);

But I only had a part of the source code..

<html lang="fr"><head><meta charset="UTF-8"><meta content="width=device-width,minimum-scale=1.0" name="viewport"><meta content="telephone=no" name="format-detection"><meta content="address=no" name="format-detection"><meta content="origin" name="referrer"><meta content="notranslate" name="google"><link href="/images/branding/product/1x/gsa_android_144dp.png" rel="icon"><meta content="/images/branding/googleg/1x/googleg_standard_color_128dp.png" itemprop="image"><link href="/manifest?pwa=webhp" crossorigin="use-credentials" rel="manifest"><style data-iml="1647545277717">@font-face{font-family:'Google Sans';font-style:normal;font-weight:400;font-display:optional;src:local('Google Sans Regular'),local('GoogleSans-Regular'),url(//fonts.gstatic.com/s/googlesans/v14/4UaGrENHsxJlGDuGo1OIlL3Kwp5eKQtGBlc.woff2)format('woff2');unicode-range:U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116;}@font-face{font-family:'Google Sans';font-style:normal;font-weight:400;font-display:optional;src:local('Google Sans Regular'),local('Goo

But it's only a small part of the really google html code... Do you have any idea where could be the problem?

**Comment by KazuCocoa** [comment]
Could you share the full appium log?

**Comment by mygoa** [comment]
Hi, 

I tried the same code with a selenium browser, and I got the exact same issue. It seems to the issue is more related to my poor knewledge of the dart language than really appium_driver. I close the issue
