### ISSUE TITLE
How to get an element attribute value ?

### ISSUE THREAD

**Issue by mbilbiesi** [KazuCocoa/appium_dart#43]
Hello, Thanks for the effort you've put into dart client; I start doing some experiment here, and I came into situation to get an element attribute value.

I have an element which has "content-desc" attribute with some text value, I tried to find a similar case from the examples you have in this project, but I could not find any case, Can you please share how to deal with this!

Thanks in advance

**Comment by KazuCocoa** [comment]
What about something like `e.attributes['content-description'];`?
https://pub.dev/documentation/appium_driver/latest/appium_driver.io/AppiumWebElement-class.html

**Comment by mbilbiesi** [comment]
Thanks KazuCocoa, Works !
