### ISSUE TITLE
Executing scroll command

### ISSUE THREAD

**Issue by mbilbiesi** [KazuCocoa/appium_dart#44]
Hello @KazuCocoa ,

I am trying to use `flutter : scrollUntilVisible` command, Can you please provide an example in dart client ?

Thanks in advance :)

**Comment by KazuCocoa** [comment]
It should be somehing like https://github.com/KazuCocoa/appium_dart/blob/main/test/functional/appium_dart_test.dart#L47-L49

**Comment by mbilbiesi** [comment]
Thanks @KazuCocoa 
`await driver.execute('flutter:scrollUntilVisible', [
      {
        'ELEMENT':AppiumFlutterFinder.byType('ListView')
      },
      {
        'item': AppiumFlutterFinder.byText("+ 43"),
        'dxScroll' : 90,
        'dyScroll': -400
      }
    ]);`
    
    the example you provided helped me!
