### ISSUE TITLE
Unable to run test on BrowserStack

### ISSUE THREAD

**Issue by mbilbiesi** [KazuCocoa/appium_dart#45]
Hello,

After I **successfully ran the test on a local Appium server**; I tried to run it on BrowserStack; I followed the instructions in the following:
https://www.browserstack.com/guide/test-flutter-apps-on-android

But whenever I run the test I am getting the following error:

```
package:appium_driver/src/handler/w3c/session.dart 27:16  W3cSessionHandler.parseCreateResponse
package:webdriver/src/common/request_client.dart 96:32    AsyncRequestClient.send

type 'Null' is not a subtype of type 'String'
```

Below is the capabilities which I am using:

```
 static Map<String, Object> browserStackAndroidDesiredCapabilitiesApp = {
    'platformName': 'Android',
    'os_version': '9.0',
    'device': 'Google Pixel 3',
    'app' : 'bs://c90375b5e7778889781f9cd8599bda62129cd94c',
    'project' : 'Appium Flutter Driver',
    'name' : 'login',
    'automationName': 'flutter',
    'unicodeKeyboard': 'true',
    'resetKeyboard': 'true',
    'clearSystemFiles': 'true',
    'disableWindowAnimation': 'true',
    'autoGrantPermissions': 'true',
    'language': 'en',
    'locale': 'US',
    'newCommandTimeout': 300,
    'autoAcceptAlerts': 'true',
    'reduceMotion': 'true'
  };
```
And here is my creation for the driver:

```
void main() {
  late AppiumWebDriver driver;

  setUpAll(() async {
    driver = await createDriver(
        uri: Uri.parse('https://MyUsername:MyPassword@hub-cloud.browserstack.com/wd/hub/'), desired: browserStackAndroidDesiredCapabilitiesApp);
  });
```

Maybe any advice or hint about what's going wrong to instantiate the drive ?

**Comment by mbilbiesi** [comment]
I found the cause of this issue right after I posted it 😄 

it is because of one wrong capability I pass which is `'device': 'Google Pixel 3' `, it needs to be 'deviceName': `'Google Pixel 3'`

the **parseW3cResponse** method under `~/.pub-cache/hosted/pub.dartlang.org/webdriver-3.0.0/lib/src/handler/w3c/utils.dart:10` showed me this issue after I switched to debug mode.

the current logs does not return any clear message; probably this needs to be improved.

**Comment by mbilbiesi** [comment]
I tried to push a commit to handle exception when we construct SessionInfo() instance, but it seems this project is not open to create a pull request

**Comment by KazuCocoa** [comment]
I modified https://github.com/KazuCocoa/appium_dart/blob/main/test/functional/appium_dart_test.dart to raise an error, then current latest version handled the error as below properly.

```
kazu $ pub run test test/functional/appium_dart_test.dart --chain-stack-traces
00:01 +0 -1: Click a button [E]                                                                                                                                                                                                                                                                                                                                                                                                                                                        
  InvalidArgumentException (400): 'automationName' can't be blank
  package:webdriver/src/handler/w3c/utils.dart 39:9         parseW3cResponse
  package:appium_driver/src/handler/w3c/session.dart 25:21  W3cSessionHandler.parseCreateResponse
  package:webdriver/src/common/request_client.dart 96:32    AsyncRequestClient.send
```

I guess... the error response was 200 plus error messages, which was valid for MJSONWP, actually but this library follows w3c.


Would you be possible to get the error response from the BrowserStack if you have time? If could... the http status code and the body is great...

We can keep the #46 error handling for non-w3c response, but then probably we can improve the error message as well.

**Comment by mbilbiesi** [comment]
Hi @KazuCocoa Yes sure, Here is the response; 
<img width="1113" alt="Screenshot 2022-11-04 at 10 08 45" src="https://user-images.githubusercontent.com/16744683/199935475-1f1fb819-c21e-436b-bf4a-667ff6e8717a.png">

```
statusCode = 200
reasonPhrase = "OK"
body = {"value":{"error":"[BROWSERSTACK_MISSING_CAPS] The [\"deviceName\"] capabilities are missing in your test script. Please refer to our capability builder - https://www.browserstack.com/app-automate/capabilities?tag=w3c","message":"[BROWSERSTACK_MISSING_CAPS] The [\"deviceName\"] capabilities are missing in your test script. Please refer to our capability builder - https://www.browserstack.com/app-automate/capabilities?tag=w3c"},"sessionId":"","status":13}
```

**Comment by KazuCocoa** [comment]
Thank you!

I see.. then their response was kind of mixed one. Selenium clients by Selenium Project can handle such cases as well, but it is not vanilla W3C spec behavior. I'll tweak the error case a bit, but the PR is correct

**Comment by KazuCocoa** [comment]
pushed a patch version with  the error message handling.

Thank you!

**Comment by mbilbiesi** [comment]
Thanks @KazuCocoa , I see a better handling for the case now 😊
