### ISSUE TITLE
Finding ID for different widget properties

### ISSUE THREAD

**Issue by Nowshin23** [KazuCocoa/appium_dart#54]
test('byKeyValueInt', () {
    expect(AppiumFlutterFinder.byKeyValueInt(42),
        'eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlU3RyaW5nIjo0Miwia2V5VmFsdWVUeXBlIjoiaW50In0=');
  });

how are you getting the "eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlU3RyaW5nIjo0Miwia2V5VmFsdWVUeXBlIjoiaW50In0=')" id to compare with?

**Comment by KazuCocoa** [comment]
That was base 64 encoded query to the Dart VM, so it is not an actual element.
So far, you can compare only via `.text` or attribute values only since the finder is just a query to the Dart VM.

**Comment by KazuCocoa** [comment]
Maybe creating a ticket in https://github.com/appium-userland/appium-flutter-driver is better place.
(If someone watching the repo have ideas, they will help it)
