### ISSUE TITLE
[Question] Appium is compatible is web platform to perform integration testing

### ISSUE THREAD

**Issue by pdax-shan** [KazuCocoa/appium_dart#57]
hi @KazuCocoa ,

im just exploring tool to use for my automation integration testing for my project im just wondering if **appium** is compatible in web platform and does appium accept higher version of flutter sdk ? thank you.

**Comment by KazuCocoa** [comment]
No, Web app is not supported by https://github.com/appium/appium-flutter-driver

> does appium accept higher version of flutter sdk ?

Like which version? So far, v3 should work
