### ISSUE TITLE
[iOS] getAvailableContexts() not working for Flutter Automation on iOS

### ISSUE THREAD

**Issue by MewanWA** [KazuCocoa/appium_dart#61]
Hi.

We are using this to write some tests in dart for testing different flows of our app. In Android its working as expected. However, in iOS when we await driver.getAvailableContexts() Future. This is due to that function returning a Future<List<String>>, which Android does, but on iOS it returns a Dynamic array with a Map and a String.

Is there another way to go about this? 

Or else I was thinking of updating it to return List<dynamic> so it can be handled anyway the user wants to, or simple normalising both platforms to return List<String> by manipulating it.

**Comment by MewanWA** [comment]
I can confirm updating the function to return List<dynamic> fixes the issue. Only difference being we, the users need to manually decode it to the type we want it to be in. Which I think is fair. Just that it needs to be documented.

Below is the code I used to return it as a List<String> for both platforms.

```
   if (defaultTargetPlatform == TargetPlatform.iOS) {
      List<dynamic> availableContexts = await contexts.getAvailableContexts();
      final List<String> iosContexts = availableContexts
          .map((item) {
            if (item is Map && item.containsKey('id')) {
              return item['id'] as String;
            } else if (item is String) {
              return item;
            }
            return null;
          })
          .whereType<String>()
          .toList();

      return iosContexts;
    } else {
      final List<dynamic> androidContexts =
          await contexts.getAvailableContexts();
      return androidContexts.cast<String>();
    }
```

**Comment by KazuCocoa** [comment]
Did you enable `appium:fullContextList`? It adds additional info to the response. I would recommend using https://appium.github.io/appium-xcuitest-driver/latest/reference/execute-methods/#mobile-getcontexts instead if you'd like to get such extra info as well. (Android as well)

> Returns the detailed information on contexts for the [Get Contexts](https://appium.io/docs/en/latest/guides/context/) command. If this capability is enabled, then each item in the returned contexts list would additionally include WebView title, full URL and the bundle identifier. Defaults to false

https://appium.github.io/appium-xcuitest-driver/latest/reference/capabilities/

**Comment by MewanWA** [comment]
@KazuCocoa Ahh. That was the reason. I have removed the fullContextList option and now its returning an array of strings on both iOS and Android. Thank you!
